### ISSUE TITLE
[Feat] add a repo prefix to use local registry

### ISSUE THREAD

**Issue by JrCs** [poseidon/terraform-render-bootkube#23]
Hi,
is it possible to add a variable that it's value is used to prefix docker images like kubeadm does with the KUBE_REPO_PREFIX environnement variable ?
With that the images can be fetch from a local docker registry instead of downloaded from the internet.

**Comment by dghubble** [comment]
Extending https://github.com/poseidon/terraform-render-bootkube/blob/master/variables.tf#L60 would offer some more flexibility (e.g. using dev images, bumping a single version, per-image mirror prefixes) than introducing a new variable and special casing for image prefixes.

**Comment by dghubble** [comment]
The underlying desire should be addressed by #25. Its a bit more effort to explicitly customize each image, but doing it this way allows for several additional use cases and it was the original hope for the `container_images` variable.

Please re-open if that doesn't solve for you.

**Comment by JrCs** [comment]
The #25 can resolve my problem, but i need to maintain the list of images/tags for every version of bootkube only to use private registry.
Can you merge #24 also so users who just need to point to a private registry can do it easily ?
