### ISSUE TITLE
[question] Why does this repo bundle manifests?

### ISSUE THREAD

**Issue by colemickens** [poseidon/terraform-render-bootkube#32]
Why does this repo bundle manifests when bootkube seems to directly embed them? https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go

Flexibility? So you can rev faster or without having to vendor a fork of bootkube just to change manifest functionality?

Thanks!

**Comment by dghubble** [comment]
Hm, "bundle"? This Terraform module replaces `bootkube render`. It aims to produce nearly the same set of output files in a directory of your choosing. No binary to install. Higher level modules (like Typhoon) can use it directly.

Backstory: In the past, terraform modules were used to define infrastructure for clusters (lbs, DNS reconds, instances, user-data, Ignition, etc) and then you'd go to [bootkube](https://github.com/kubernetes-incubator/bootkube), download bootkube into your path, and run bootkube render with arguments (still shown in README for comparison). With multiple clusters it gets bothersome and if you want to make a pipeline / system to launch clusters for you, you have to keep the binary up to date. And you need the right architecture. And if you have a team everyone needs the right version. Etc. It became easier to have a re-usable Terraform module.

**Comment by colemickens** [comment]
Makes a lot of sense. Thanks!
