### ISSUE TITLE
Explore Kubelet TLS bootstrap once attestation is in place

### ISSUE THREAD

**Issue by dghubble** [poseidon/terraform-render-bootkube#41]
We've chosen not to adopt kubelet TLS bootstrap in this module. Rendered assets continue to generate a kubeconfig that should be distributed to nodes.

### Background

bootkube [v0.10.0](https://github.com/kubernetes-incubator/bootkube/releases/tag/v0.10.0)'s kubelet TLS bootstrap feature, in its current form, does not provide compelling enhancements for module users or for the primary user, the Typhoon distro. The feature requires host changes,  changes to secret distribution, and to the way kubelets get a kubeconfig.

* Nodes are given a token instead of a generated kubeconfig
* Nodes generate CSR's that are submitted to the apiserver
* The apiserver is configured to hand out kubeconfigs to nodes
* The apiserver does not perform attestation. The token is the only proof the node is not a malicious agent.

As a result, the token must be safeguarded exactly like a kubeconfig. Theft of the token means an adversary can exchange it for a kubeconfig. Additionally, a kubeconfig still needs to be generated for admin use. For users, this would cause disruption/changes without real security benefit. It has the added risk that the apiserver is configured to hand out kubeconfigs.

### Future

However, Kubelet TLS bootstrap has some longer term plans to provide a more compelling security story. This issue is opened to:

1) Highlight the divergence from bootkube and why
2) Check back to see if kubelet TLS bootstrap becomes complelling.

**Comment by klausenbusk** [comment]
It is worth noticing, that TLS bootstrapping currently isn't compatible with [CCM](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#chicken-and-egg). A ex is [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) which provide tighter integration with DO.

**Comment by bcg62** [comment]
would it still be feasible to configure controller-manager with `--cluster-signing-cert-file` and `--cluster-signing-key-file` ?

without them it leaves CSR functionality unusable. `kubectl certificate approve` will approve a CSR but never issue a cert.

this is useful when trying to manage or automate user access natively in kubernetes

**Comment by dghubble** [comment]
They way TLS bootstrapping closes the door on CCM, I'm not currently planning to pursue adopting it. Statically generated certificates work well enough and CCM has a decent shot of providing compelling value soon-ish.
