### ISSUE TITLE
etcd-tls multi-master issue,  tls: bad certificate

### ISSUE THREAD

**Issue by bkcsfi** [poseidon/terraform-render-bootkube#46]
I am using module bootkube source = "git::https://github.com/poseidon/terraform-render-bootkube.git?ref=070d1846448252acc8ebe6d40aaa555e65b69b85"

I can get a k8s cluster to start with a single master and 2 workers. However when I try with 3 master nodes etcd fails to accept other etcd members

example error from journalctl -u etcd-member  (from 1st master node - 10.1.250.190)

```
I | embed: rejected connection from "10.1.250.191:44158" (error "remote error: tls: bad certificate",  ServerName "")
```
3 master nodes have IP addresses and ip names

* 10.1.250.190 - dev-001-etcd0.sfi.ca
* 10.1.250.191 - dev-001-etcd1.sfi.ca
* 10.1.250.192 - dev-001-etcd2.sfi.ca

controller.yml 

```
ETCD_IMAGE_TAG=v3.3.1
etcd_initial_cluster:
  etcd0=https://10.1.250.190:2380,etcd1=https://10.1.250.191:2380,etcd2=https://10.1.250.192:2380
```

when I login to 10.1.250.190 (etcd0), I check dns ptr lookup

```
dig -x 10.1.250.191

; <<>> DiG 9.10.2-P4 <<>> -x 10.1.250.191
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32542
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;191.250.1.10.in-addr.arpa.     IN      PTR

;; ANSWER SECTION:
191.250.1.10.in-addr.arpa. 26   IN      PTR     dev-001-etcd1.sfi.ca.
```

and forward lookup

```
dig dev-001-etcd1.sfi.ca

; <<>> DiG 9.10.2-P4 <<>> dev-001-etcd1.sfi.ca
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43223
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dev-001-etcd1.sfi.ca.          IN      A

;; ANSWER SECTION:
dev-001-etcd1.sfi.ca.   216     IN      A       10.1.250.191
```
looking at the certificate,  openssl x509 -in etcd-client.crt -noout -text

shows in-part

```
Issuer: O=etcd, CN=etcd-ca
Subject: O=etcd, CN=etcd-client

X509v3 Subject Alternative Name: 
	DNS:dev-001-etcd0.sfi.ca, DNS:dev-001-etcd1.sfi.ca, DNS:dev-001-etcd2.sfi.ca, DNS:localhost, IP Address:127.0.0.1
```
Looking at coreos etcd tls information page https://coreos.com/etcd/docs/latest/op-guide/security.html in the "Notes for TLS authentication" section

I think the certificate would work if either of the following were true:

* ip address 127.0.0.1 was not included in SAN

* ip addresses 10.1.250.190, 10.1.250.191, 10.1.250.192 were added in addition to 127.0.0.1

Do you think my tls issue is related to this, and if so would it be reasonable to allow an optional list of etcd_servers_ip_address to be passed into bootkube module so they can be appended to the ip_address list along with 127.0.0.1 ?

**Comment by bkcsfi** [comment]
probably this issue is invalid, I am still investigating

I did fork and add list of ip address to etcd-tls.tf

I am still getting the same errors on the master (and likely other nodes) as specified above

I also see  errors like this

```
rafthttp: health check for peer 50039f081f5864d could not connect: x509: cannot validate certificate for 10.1.250.191 because it doesn't contain any IP SANs
```
x509 output looks like what I wanted

```
X509v3 Subject Alternative Name: 
	DNS:dev-001-etcd0.sfi.ca, DNS:dev-001-etcd1.sfi.ca, DNS:dev-001-etcd2.sfi.ca, DNS:localhost, IP Address:10.1.250.190, IP Address:10.1.250.191, IP Address:10.1.250.192, IP Address:127.0.0.1
```

However on .190 node I can run this ok

```
curl -k --cert /opt/bootkube/assets/tls/etcd-client.crt --key /opt/bootkube/assets/tls/etcd-client.key https://10.1.250.190:2380/members
[{"id":360351675324925517,"peerURLs":["https://10.1.250.191:2380"],"name":"etcd1"},{"id":7090232047322873607,"peerURLs":["https://10.1.250.192:2380"],"name":"etcd2"},{"id":7562789541247032687,"peerURLs":["https://10.1.250.190:2380"],"name":"etcd0"}]
```
So it seems that the etcd peers are accepting each other, and that the tls bad cert must be caused by some other process (maybe I've mis-configured apiserver on the other nodes to talk only to master)

though I'm not sure why raft errors are showing up..

oops, node .191 doesn't have /opt/bootkube/assets folder.. I must have goofed up my typhoon fork.

will respond when I know more. sorry for the noise

**Comment by dghubble** [comment]
Typhoon clusters (except GCP) can have multiple controllers (i.e. masters) which means they have multiple etcd peers. You may wish to look at those in detail. Without looking into this much yet, I suspect it may be an issue with your usage.

**Comment by dghubble** [comment]
You should strongly favor configuring etcd peers to refer to each other by DNS name and minting TLS certificates which use DNS SANs. Its more flexible and appropriate for use with TLS (i.e. if you ever need to replace a peer gracefully, the DNS record indirection comes in handy). I don't think I'd take a PR to start allowing IP addresses.

**Comment by bkcsfi** [comment]
I am closing this ticket as my issue was not related to terraform-render-bootkube. 

As dghubble suggested, the issue was related to my choice of relying on IP addresses for nodes rather than configuring DNS names for controllers and workers.

Specifically when bootkube module etcd_servers variable contains IP addresses, etcd will report the tls error reported in this ticket.  Additionally, using only IP addresses will break multi-controller setups because the bootkube module api_servers variable will not resolve to round-robin controller nodes via dns
