### ISSUE TITLE
Kube-api-server admission control order

### ISSUE THREAD

**Issue by balchua** [poseidon/terraform-render-bootkube#47]
I noticed that the current admission control set and order differs from the recommended list as stated in kubernetes.io documentation. 

From the documentation, Kubernetes version >=1.9, it is strongly recommended the following set and order.
`   --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota  `

The current admission controller defined in the assets are 

`   --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ValidatingAdmissionWebhook,ResourceQuota,DefaultTolerationSeconds,MutatingAdmissionWebhook  `

It doesn't have `PersistentVolumeLabel` as well the order is a little bit off.  So far i have not seen any side effect, but would it be better off following the recommendation?

**Comment by balchua** [comment]
I just realized that PersistentVolumeLabel is deprecated.

**Comment by dghubble** [comment]
`terraform-render-bootkube` mirrors the ordering used for self-hosted Kubernetes clusters ala [kubernetes-incubator/bootkube](https://github.com/kubernetes-incubator/bootkube) so if you experience an issue, please report it there.

Yes, `PersistentVolumeLabel` is deprecated.

**Comment by balchua** [comment]
Ok. Closing the issue.
