### ISSUE TITLE
Allow variables for certificate validity period

### ISSUE THREAD

**Issue by mleklund** [poseidon/terraform-render-bootkube#53]
Though unlikely a cluster would not be upgraded within a year, I would like the option of setting certificate validity to something higher.

I am willing to provide a pull request if it is something you are willing to accept.

**Comment by dghubble** [comment]
One year feels like an ok amount of time. Long enough to be practical, short enough it can't be written off. A cluster that hasn't been blue/green replaced after a year is 3-4 Kubernetes releases behind (they patch the prior 2).

Do you have a particular case in mind?

**Comment by mleklund** [comment]
My intention was to leave it at 1 year but make it a variable.  

Allowing k8 and etcd carts to be set as is best practice in their own organizations.  

Mike E.

**Comment by dghubble** [comment]
I wouldn't want to bubble this option up to Typhoon, so I'm going to pass. For those that are really motivated to set a longer expiration, having to fork and make the tweak is just enough of a little hurdle that it makes it clear they're deviating from good practice.

In future we'll be switching to rotating certs anyway.
