### ISSUE TITLE
HA Kubernetes environment does not work for me

### ISSUE THREAD

**Issue by kratan** [poseidon/terraform-render-bootkube#78]
Hi,
im using typhoon together with render-bootkube. Following problems i have in my setup:
- replica are hardcoded to "2", normally replicas of kube-controller-manager, kube-scheduler should be the same as count(masters), maybe replacing "2" with spec:
`  ${length(split(",",etcd_servers))} `

- another problem in my setup is, that in bare metal cl kube-scheduler, kube-controller-manager these deployments only binded to one node. So i have running 2 replicas of kube-scheduler/kube-controller-manager on one node. normally it should look like http://sysadvent.blogspot.com/2017/12/day-24-on-premise-kubernetes-with.html

greets

**Comment by dghubble** [comment]
Duplicate schedulers and controller-managers is generally enough and HA. Container Linux clusters regularly coordinate reboots of a node at a time. Power cycle more than that and you can have a temporary control plane outage, though application workloads and ingress won't be affected.

I see your concern though. If you had many masters (say 5), you might want more than duplicate schedulers / controller-managers. Right now, you'd manually `kubectl scale` those deployments to the number you prefer.

Considering a different default, the replica count can't just be the number of controllers - even single-controller clusters should run at least 2 to ensure `kubectl edit` of control plane components are supported properly.

Concerning schedulers or controller-managers running colocated on the same node, both deployments already make use of anti-affinity to help avoid that scheduling layout.

**Comment by kratan** [comment]
Hi,
thanks for replying.
anti-affinity is only set to preferred.... not to required.... so in most cases controllers/ schedulers pods are bind to the same node because there is maybe just one master-node online during setup(other nodes get online later, but of course the pods does not get rescheduled on other nodes if they get online to have HA)

In most cases master nodes have the same hardware(virt/phy), is there any reason why not have running all services belonging to a master on each master node? If you want real HA i guess you should always deal with three redundant nodes for the master HA.

Of course i can scaling on my own, but maybe having it out the box it would be great...

..thanks for reading :)

**Comment by dghubble** [comment]
Its known and accepted they can end up on the same node. Anti-affinity should be "preferred", not "required" - on single-master clusters, the 2nd scheduler or controller-manager wouldn't schedule. And just running one per master isn't enough in the single master case either, there should be at least two of each even in single-master clusters for edits.

I may increase the number, but this design itself was decided upon as the best way to provide support both single-master and multiple-master clusters.

**Comment by dghubble** [comment]
Not changing the affinity, but #81 raises the replica count for multi-master (no affect on single-master).

**Comment by dghubble** [comment]
You could experiment with deploying a https://github.com/kubernetes-incubator/descheduler if you'd like to move pods around after bootstrapping.
