### ISSUE TITLE
Increasing availability of cluster DNS service

### ISSUE THREAD

**Issue by elemental-lf** [poseidon/terraform-render-bootkube#80]
Taking into account the fact that auto-scaling isn't enabled in ``terraform-render-bootkube`` wouldn't it make sense to run at least two coredns pods to make upgrades and pod recreations triggered by other deployment changes seamless? I think podAntiAffinity rules similar to the ones used for ``kube-scheduler`` might be also be useful. What are your thoughts on this?

**Comment by dghubble** [comment]
I agree, without a pod nanny or auto-scale mechanism like kube-dns had, its a better default to run at least 2, and up to the number of masters.

**Comment by elemental-lf** [comment]
Great, thanks!
